export enum OutputActionTypes {
  ONCHANGE_OUTPUT = "ONCHANGE_OUTPUT",
  ONCHANGE_CLEAR_OUTPUT = "ONCHANGE_CLEAR_OUTPUT",
  ONCHANGE_IS_MINUS = "ONCHANGE_IS_MINUS",
  ONCHANGE_CALCULATE = "ONCHANGE_CALCULATE",
  ONCHANGE_IS_OPERATOR_CLICK = "ONCHANGE_IS_OPERATOR_CLICK",
}
